services:
  # Serviço de banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: taskflow-postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskflow-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serviço do backend Spring Boot
  backend:
    build:
      context: ./task-app-backend
      dockerfile: Dockerfile
    container_name: taskflow-backend
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/taskdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: meuSegredoSuperSecretoParaGerarTokens
      JWT_EXPIRATION: 86400000
      SERVER_PORT: 8080
      FRONTEND_URL: http://localhost:4200
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - taskflow-network

  # Serviço do frontend Angular
  frontend:
    build:
      context: ./task-app-frontend
      dockerfile: Dockerfile
    container_name: taskflow-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - taskflow-network

networks:
  taskflow-network:
    driver: bridge

volumes:
  postgres_data: